### ISSUE TITLE
Multiple substitutions with same starting location lead to assertion failure

### ISSUE THREAD

**Issue by vasilisp** [janestreet/camlp4-to-ppx#1]
Running `camlp4-to-ppx` on programs using `js_of_ocaml` syntax leads to assertion failures. For example, consider the following fragment:

``` ocaml
let _ = foo##bar("")
```

The assertion [`pos <= start && start <= stop` inside `do_output`](https://github.com/janestreet/camlp4-to-ppx/blob/0dba3520d766a93c5d6ac5e2d93f7af6101bb881/lib/camlp4_to_ppx.ml#L50) fails. The reason is that `pa_js` performs multiple substitutions starting at the same point, but these are not applied in the correct order.

[Sorting](https://github.com/janestreet/camlp4-to-ppx/blob/0dba3520d766a93c5d6ac5e2d93f7af6101bb881/lib/camlp4_to_ppx.ml#L55) with standard polymorphic `compare` (lexicographic comparison) seems to fix the issue.

**Comment by ghost** [comment]
Indeed. I pushed a fix. I still used a custom-comparison function to make the intent explicit.

**Comment by vasilisp** [comment]
Nice, thanks. Surely better than standard `compare`.
