### ISSUE TITLE
Mistranslation of jsnew

### ISSUE THREAD

**Issue by vouillon** [janestreet/camlp4-to-ppx#2]
@hhugo 
The following piece of code:
`fun f a b -> jsnew f(a,b)`
is mistranslated into:
`fun f a b -> new%js fab`
instead of:
`fun f a b -> new%js f a b`.

**Comment by vouillon** [comment]
Great! Thanks!

**Comment by dbuenzli** [comment]
Here's another problem with `jsnew`: 

```
- let p = jsnew (Js.Unsafe.variable "DOMParser") () in
+ let p = new%js (Js.Unsafe.variable "DOMParser") in
```

should be: 

```
let p = Js.Unsafe.variable "DOMParser" in 
let p = new%js p in
```
